-- Create FINGERPRINT_SHIFTS table
CREATE TABLE FINGERPRINT_SHIFTS (
    SHIFTTYPE VARCHAR(1),
    DATETIMEIN DATETIME,
    TIMEIN VARCHAR(11),
    DATEOUT DATE,
    TIMEOUT VARCHAR(11),
    SHIFT VARCHAR(1),
    CONSTRAINT FINGERPRINT_SHIFTS_UK1 UNIQUE (SHIFT, DATETIMEIN),
    CONSTRAINT CKECK_VALUE_PRINTTYPE CHECK (SHIFT IN ('A', 'B', 'C', 'D'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create FINGERPRINT24 table
CREATE TABLE FINGERPRINT24 (
    PRINTTYPE VARCHAR(26) NOT NULL,
    PRINTTIME VARCHAR(26) NOT NULL,
    PRINTDATE DATE NOT NULL,
    CIVILID DECIMAL(14,0) NOT NULL,
    ID DECIMAL(12,0) NOT NULL,
    MASTERID DECIMAL(10,0),
    USERID DECIMAL(10,0),
    CRDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FINGERPRINT24_PK PRIMARY KEY (ID),
    CONSTRAINT CKECK_VALUE_PRINTTYPE_F24 CHECK (PRINTTYPE IN ('f1', 'f2'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create EMPINFO table
CREATE TABLE EMPINFO (
    CIVILID DECIMAL(10,0) NOT NULL,
    FILNO DECIMAL(10,0),
    EMPNAME VARCHAR(100) NOT NULL,
    SECID DECIMAL(10,0) NOT NULL,
    HIREDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SEX VARCHAR(8),
    CARD DECIMAL(10,0) DEFAULT 1,
    EMPID DECIMAL(10,0) NOT NULL,
    CONSTRAINT EMPINFO_PK PRIMARY KEY (CIVILID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
